const fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto');
(async()=>{process.env.NODE_ENV='development';process.env.DEV_DATABASE='pglite';process.env.DEV_DATABASE_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'logic-browser-'));process.env.PORT='0';process.env.SESSION_SECRET=crypto.randomBytes(32).toString('hex');process.env.TOTP_ENCRYPTION_KEY=crypto.randomBytes(32).toString('hex');delete process.env.DATABASE_URL;delete process.env.PUBLIC_ORIGIN;
const {server,db}=await require('../server/app').start(),base='http://127.0.0.1:'+server.address().port;const {chromium}=require('playwright'),binary=require('@sparticuz/chromium').default;const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||await binary.executablePath(),args:binary.args});const page=await browser.newPage({reducedMotion:'reduce'}),errors=[],overflow=[];
page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!==base&&!u.href.startsWith('data:'))r.abort();else r.continue()});
const root=path.resolve(__dirname,'..'),routes=fs.readdirSync(root).filter(x=>x.endsWith('.html')).map(x=>'/'+x).concat(fs.readdirSync(path.join(root,'courses')).filter(x=>x.endsWith('.html')).map(x=>'/courses/'+x),['/blog/ca-foundation-roadmap.html','/results/ca.html','/admin/']);
for(const width of [1920,1440,1366,1024,768,430,390,375,360]){await page.setViewportSize({width,height:1000});for(const route of routes){await page.goto(base+route,{waitUntil:'domcontentloaded'});await page.waitForTimeout(30);const dims=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));if(dims.scroll>width+2)overflow.push({width,route,scroll:dims.scroll});}console.log('Checked '+width+'px across '+routes.length+' routes');}
fs.mkdirSync(path.join(root,'test-output'),{recursive:true});await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/');await page.screenshot({path:path.join(root,'test-output/home-desktop.png'),fullPage:false});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'test-output/home-mobile.png'),fullPage:false});await page.goto(base+'/results.html');await page.screenshot({path:path.join(root,'test-output/results-mobile.png'),fullPage:false});
const password=crypto.randomBytes(16).toString('hex');await db.query('INSERT INTO admin_users(username,password_hash) VALUES($1,$2)',['browser',await require('bcryptjs').hash(password,4)]);await page.goto(base+'/admin/');await page.locator('[name=username]').fill('browser');await page.locator('[name=password]').fill(password);await page.locator('#loginForm button').click();await page.locator('#appView:not(.hidden)').waitFor();await page.goto(base+'/admin/content.html');await page.locator('#records button').first().waitFor();await page.locator('#records button').first().click();await page.locator('[name=title]').waitFor();console.log('Admin browser login and content editor verified');
await browser.close();await new Promise(r=>server.close(r));await db.close();fs.rmSync(process.env.DEV_DATABASE_DIR,{recursive:true,force:true});const result={routes:routes.length,widths:[1920,1440,1366,1024,768,430,390,375,360],errors:[...new Set(errors)],overflow};fs.writeFileSync(path.join(root,'test-output/browser-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));process.exit(result.errors.length||overflow.length?1:0);
})().catch(e=>{console.error(e);process.exit(1)});
