const fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
(async()=>{
 Object.assign(process.env,{NODE_ENV:'development',DEV_DATABASE:'pglite',DEV_DATABASE_DIR:fs.mkdtempSync(path.join(os.tmpdir(),'logic-cms-browser-')),SESSION_SECRET:crypto.randomBytes(32).toString('hex'),TOTP_ENCRYPTION_KEY:crypto.randomBytes(32).toString('hex'),PORT:'0'});delete process.env.DATABASE_URL;delete process.env.PUBLIC_ORIGIN;
 const root=path.resolve(__dirname,'..'),original=fs.readFileSync(path.join(root,'index.html')),output=path.join(root,'test-output');fs.mkdirSync(output,{recursive:true});
 const {server,db}=await require('../server/app').start(),base='http://127.0.0.1:'+server.address().port;const binary=require('@sparticuz/chromium').default,browser=await require('playwright').chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||await binary.executablePath(),args:binary.args});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[],overflows=[];let uploaded='';
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
 const check=async()=>{const d=await page.evaluate(()=>({w:innerWidth,s:document.documentElement.scrollWidth}));if(d.s>d.w+2)overflows.push({url:page.url().replace(base,''),...d});};
 try{
 const password=crypto.randomBytes(20).toString('hex');await db.query('INSERT INTO admin_users(username,password_hash) VALUES($1,$2)',['browser',await require('bcryptjs').hash(password,4)]);
 await page.goto(base+'/admin/');await page.locator('[name=username]').fill('browser');await page.locator('[name=password]').fill(password);await page.locator('#loginForm button').click();await page.locator('#appView:not(.hidden)').waitFor();
 await page.locator('button[data-section=pages]').click();const frame=page.frameLocator('#pageFrame');await frame.locator('[data-record-id=ca] h3').click();assert.match(await page.locator('#selectedElementName').textContent(),/h3/);await page.locator('#elText').fill('CA browser edit');await page.locator('#applyElement').click();assert.equal(await frame.locator('[data-record-id=ca] h3').textContent(),'CA browser edit');await frame.locator('[data-record-id=ca] .program-icon img').click();assert.equal(await page.locator('#srcRow').isVisible(),true);await page.locator('#selectParentElement').click();assert.match(await page.locator('#selectedElementName').textContent(),/article/);await page.locator('#savePage').click();await page.locator('#pageSaveState').filter({hasText:'Saved just now'}).waitFor();assert.match(await (await fetch(base+'/')).text(),/CA browser edit/);console.log('Programme text selection, image selection and Page Editor persistence passed');
 await page.goto(base+'/admin/layout.html#header');await page.locator('[name="layout.applyText"]').fill('Book a visit');await page.locator('[name="layout.applyUrl"]').fill('/contact.html');await page.getByRole('button',{name:'Save globally',exact:true}).click();await page.locator('#layoutStatus').filter({hasText:'Saved globally'}).waitFor();await check();await page.screenshot({path:path.join(output,'global-header-desktop.png')});
 await page.goto(base+'/admin/layout.html#footer');await page.locator('[name="layout.contactTitle"]').fill('Admissions team');await page.locator('[name="settings.tagline"]').fill('A globally editable footer');await page.getByRole('button',{name:'Save globally',exact:true}).click();await page.locator('#layoutStatus').filter({hasText:'Saved globally'}).waitFor();
 for(const route of ['/','/courses/ca.html','/results/ca.html']){await page.goto(base+route);assert.equal(await page.locator('.nav-actions .btn').textContent(),'Book a visit');assert.match(await page.locator('footer').textContent(),/A globally editable footer/);assert.equal(await page.locator('.desktop-nav .nav-resource-menu').count(),1);}
 await page.goto(base+'/admin/content.html#placement_posters');await page.locator('#contentTitle').filter({hasText:'Placement posters'}).waitFor();await page.locator('[name=title]').fill('Placement browser QA');const png=await require('sharp')({create:{width:640,height:800,channels:3,background:'#e1efe5'}}).png().toBuffer();await page.locator('#fields input[type=file]').setInputFiles({name:'cms-browser-qa.png',mimeType:'image/png',buffer:png});await page.waitForFunction(()=>document.querySelector('[name=image]').value.startsWith('/uploads/'));uploaded=await page.locator('[name=image]').inputValue();await page.locator('[name=company]').fill('QA Company');await page.locator('#recordForm button[type=submit]').click();await page.locator('#status').filter({hasText:'Saved. The website is updated.'}).waitFor();await page.locator('#records button').filter({hasText:'Placement browser QA'}).waitFor();await page.screenshot({path:path.join(output,'poster-manager-desktop.png')});
 console.log('Global layout saves and direct poster upload passed');await page.goto(base+'/placements.html');await page.locator('[data-placement-id] button').click();await page.locator('.image-lightbox:not([hidden])').waitFor();await page.keyboard.press('Escape');
 await page.goto(base+'/admin/content.html#results');await page.locator('#contentTitle').filter({hasText:'Result posters'}).waitFor();await page.locator('[name=title]').fill('Result browser QA');await page.locator('[name=image]').fill(uploaded);await page.locator('[name=categoryId]').selectOption('ca');await page.locator('[name=level]').fill('CA Foundation');await page.locator('#recordForm button[type=submit]').click();await page.locator('#status').filter({hasText:'Saved. The website is updated.'}).waitFor();
 await page.goto(base+'/admin/content.html#banners');await page.locator('#contentTitle').filter({hasText:'Banners'}).waitFor();await page.locator('[name=title]').fill('Banner browser QA');await page.locator('[name=image]').fill(uploaded);await page.locator('[name=page]').selectOption('results');await page.locator('[name=categoryId]').selectOption('ca');await page.locator('#recordForm button[type=submit]').click();await page.locator('#status').filter({hasText:'Saved. The website is updated.'}).waitFor();
 await page.goto(base+'/results.html');assert.equal(await page.locator('[data-image-lightbox]').count(),0);await page.locator('a[href="/results/ca.html"]').click();await page.locator('[data-image-lightbox]').waitFor();await page.locator('[data-banner-id]').waitFor();
 for(const width of [1440,768,390,360]){await page.setViewportSize({width,height:900});for(const route of ['/','/results.html','/results/ca.html','/placements.html','/admin/layout.html#footer','/admin/content.html#results','/admin/content.html#placement_posters','/admin/content.html#banners']){await page.goto(base+route);if(route.includes('/admin/layout'))await page.locator('[name="layout.contactTitle"]').waitFor();else if(route.includes('/admin/content')){await page.locator('#contentTitle').filter({hasText:({'results':'Result posters','placement_posters':'Placement posters','banners':'Banners'})[route.split('#')[1]]}).waitFor();await page.locator('[name=title]').waitFor();}await check();if(width===390){if(route==='/admin/layout.html#footer')await page.screenshot({path:path.join(output,'global-footer-mobile.png')});if(route==='/results.html')await page.screenshot({path:path.join(output,'result-categories-mobile.png')});if(route==='/admin/content.html#placement_posters')await page.screenshot({path:path.join(output,'poster-manager-mobile.png')});}}console.log('Affected pages and CMS checked at '+width+'px');}
 // Exercise save and delete from the narrow/mobile CMS layout as well.
 await page.goto(base+'/admin/content.html#placement_posters');await page.locator('#contentTitle').filter({hasText:'Placement posters'}).waitFor();await page.locator('#records button').filter({hasText:'Placement browser QA'}).click();await page.locator('[name=title]').fill('Placement mobile edit');await page.locator('#recordForm button[type=submit]').click();await page.locator('#status').filter({hasText:'Saved. The website is updated.'}).waitFor();await page.locator('#deleteRecord').click();await page.locator('#status').filter({hasText:'Item deleted.'}).waitFor();assert.ok(!(await (await fetch(base+'/placements.html')).text()).includes('Placement mobile edit'));
 assert.deepEqual(errors,[]);assert.deepEqual(overflows,[]);fs.writeFileSync(path.join(output,'cms-workflows.json'),JSON.stringify({passed:true,widths:[1440,768,390,360],workflows:['programme selection and persistence','global header/footer save across routes','poster upload and publish','result category navigation','category banner','mobile poster update and delete','poster lightbox'],errors,overflows},null,2));console.log('All CMS workflows passed');
 }catch(e){console.error('BROWSER STATE',page.url(),await page.locator('body').innerText(),errors);await page.screenshot({path:path.join(output,'cms-error.png')});throw e;}finally{fs.writeFileSync(path.join(root,'index.html'),original);if(uploaded)fs.rmSync(path.join(root,uploaded),{force:true});await browser.close();await new Promise(r=>server.close(r));await db.close();fs.rmSync(process.env.DEV_DATABASE_DIR,{recursive:true,force:true});}
 process.exit(0);
})().catch(e=>{console.error(e);process.exit(1)});
