const fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
(async()=>{
 Object.assign(process.env,{NODE_ENV:'development',DEV_DATABASE:'pglite',DEV_DATABASE_DIR:fs.mkdtempSync(path.join(os.tmpdir(),'logic-logos-')),SESSION_SECRET:crypto.randomBytes(32).toString('hex'),TOTP_ENCRYPTION_KEY:crypto.randomBytes(32).toString('hex'),PORT:'0'});delete process.env.DATABASE_URL;delete process.env.PUBLIC_ORIGIN;
 const {server,db}=await require('../server/app').start(),base='http://127.0.0.1:'+server.address().port,binary=require('@sparticuz/chromium').default,browser=await require('playwright').chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||await binary.executablePath(),args:binary.args}),page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
 const before=await db.get('global_settings','site'),header='/assets/course-icons/overview.svg',footer='/assets/course-icons/global.svg';
 async function check(route,h,f){await page.goto(base+route);await page.waitForLoadState('networkidle');assert.equal(await page.locator('.site-header .site-logo').getAttribute('src'),h);assert.equal(await page.locator('.footer .site-logo').getAttribute('src'),f);assert.ok(await page.locator('.site-header .site-logo').evaluate(i=>i.complete&&i.naturalWidth>0));assert.ok(await page.locator('.footer .site-logo').evaluate(i=>i.complete&&i.naturalWidth>0));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));}
 try{
 await check('/',before.logoUrl,before.logoUrl);
 const password=crypto.randomBytes(20).toString('hex');await db.query('INSERT INTO admin_users(username,password_hash) VALUES($1,$2)',['logos',await require('bcryptjs').hash(password,4)]);
 await page.goto(base+'/admin/');await page.locator('[name=username]').fill('logos');await page.locator('[name=password]').fill(password);await page.locator('#loginForm button').click();await page.locator('#appView:not(.hidden)').waitFor();
 async function save(part,url){await page.goto(base+'/admin/layout.html#'+part);await page.locator('#layoutTitle').filter({hasText:part==='header'?'Global Header':'Global Footer'}).waitFor();await page.locator('[name="layout.logoUrl"]').fill(url);await page.getByRole('button',{name:'Save globally',exact:true}).click();await page.locator('#layoutStatus').filter({hasText:'Saved globally'}).waitFor();}
 await save('header',header);await check('/',header,before.logoUrl);await save('footer',footer);await check('/',header,footer);
 for(const width of [1440,390]){await page.setViewportSize({width,height:900});for(const route of ['/','/courses/ca.html','/results/ca.html','/blog/ca-foundation-roadmap.html'])await check(route,header,footer);await page.goto(base+'/admin/layout.html#footer');await page.locator('[name="layout.logoUrl"]').waitFor();assert.equal(await page.locator('[name="layout.logoUrl"]').inputValue(),footer);await page.screenshot({path:path.join(__dirname,'../test-output/separate-logos-'+width+'.png')});}
 await save('footer','');await check('/',header,before.logoUrl);await save('footer',footer);
 const after=await db.get('global_settings','site');assert.equal(after.logoUrl,before.logoUrl);assert.deepEqual(after.tracking,before.tracking);assert.deepEqual(after.brochures,before.brochures);assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(__dirname,'../test-output/separate-logos.json'),JSON.stringify({passed:true,widths:[1440,390],routes:['/','/courses/ca.html','/results/ca.html','/blog/ca-foundation-roadmap.html'],checks:['existing logo fallback','header-only update','footer-only update','browser hydration retains both logos','saved fields survive reload','clear footer restores fallback','global branding/tracking/brochures preserved'],errors},null,2));console.log('Independent logos, fallback, reload and desktop/mobile rendering passed.');
 }finally{await browser.close();await new Promise(r=>server.close(r));await db.close();fs.rmSync(process.env.DEV_DATABASE_DIR,{recursive:true,force:true});}process.exit(0);
})().catch(e=>{console.error(e);process.exit(1)});
