const fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict');
(async()=>{
 Object.assign(process.env,{NODE_ENV:'development',DEV_DATABASE:'pglite',DEV_DATABASE_DIR:fs.mkdtempSync(path.join(os.tmpdir(),'logic-sliders-')),SESSION_SECRET:crypto.randomBytes(32).toString('hex'),TOTP_ENCRYPTION_KEY:crypto.randomBytes(32).toString('hex'),PORT:'0'});delete process.env.DATABASE_URL;delete process.env.PUBLIC_ORIGIN;
 const {server,db}=await require('../server/app').start(),base='http://127.0.0.1:'+server.address().port,binary=require('@sparticuz/chromium').default,browser=await require('playwright').chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||await binary.executablePath(),args:binary.args}),page=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'no-preference'}),errors=[],output=path.join(__dirname,'../test-output');fs.mkdirSync(output,{recursive:true});page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
 let cookie='',csrf='';async function api(p,method='GET',body){const r=await fetch(base+p,{method,headers:{Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':csrf},...(body?{body:JSON.stringify(body)}:{})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const d=await r.json();if(d.csrfToken)csrf=d.csrfToken;assert.equal(r.status,200,JSON.stringify(d));return d;}
 const unique='.success-group:not([data-slider-clone]) > .result-poster-card:not([data-slider-clone])';
 async function open(route){await page.goto(base+route);await page.locator('.success-slider').first().waitFor();await page.locator('.success-slider').first().scrollIntoViewIfNeeded();await page.mouse.move(0,0);await page.waitForFunction(()=>document.documentElement.classList.contains('logic-motion-enabled'));await page.waitForTimeout(120);}
 try{
 const password=crypto.randomBytes(20).toString('hex');await db.query('INSERT INTO admin_users(username,password_hash) VALUES($1,$2)',['sliders',await require('bcryptjs').hash(password,4)]);await api('/api/admin/session');await api('/api/admin/login','POST',{username:'sliders',password});
 for(let i=0;i<7;i++){const common={title:'QA student '+(i+1),image:'/assets/images/result-poster-'+(i%6+1)+'.svg',status:i===6?'draft':'published',order:i};await api('/api/admin/content/results/slide-'+i,'PUT',{...common,categoryId:'ca',level:'CA Foundation',studentName:'Student '+(i+1)});await api('/api/admin/content/placement_posters/slide-'+i,'PUT',{...common,company:'Company '+(i+1),course:'CA'});}
 for(const width of [1440,768,390,360]){await page.setViewportSize({width,height:1100});for(const route of ['/results.html','/results/ca.html','/placements.html']){await open(route);assert.equal(await page.locator('.success-row').count(),2);assert.equal(await page.locator(unique).count(),6);assert.ok(!(await page.locator('.success-slider').innerText()).includes('QA student 7'));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
 const values=()=>page.locator('.success-track').evaluateAll(ts=>ts.map(t=>({x:new DOMMatrixReadOnly(getComputedStyle(t).transform).m41,direction:getComputedStyle(t).animationDirection,distance:parseFloat(t.style.getPropertyValue('--success-distance')),width:t.firstElementChild.getBoundingClientRect().width,state:getComputedStyle(t).animationPlayState})));
 const a=await values();await page.waitForTimeout(250);const b=await values();assert.equal(a[0].direction,'normal');assert.equal(a[1].direction,'reverse');assert.ok(b[0].x<a[0].x,JSON.stringify({width,route,a,b}));assert.ok(b[1].x>a[1].x,JSON.stringify({width,route,a,b}));a.forEach(x=>assert.ok(Math.abs(x.distance-x.width)<1,'Loop distance must equal repeated group width'));
 assert.equal(await page.locator('[data-slider-clone] a:not([tabindex="-1"]),[data-slider-clone] button:not([tabindex="-1"])').count(),0);
 await page.locator('.success-toggle').click();assert.equal(await page.locator('.success-slider.is-paused').count(),1);assert.equal(await page.locator('.success-track').first().evaluate(e=>getComputedStyle(e).animationName),'none');await page.locator('.success-toggle').click();await page.mouse.move(0,0);assert.notEqual(await page.locator('.success-track').first().evaluate(e=>getComputedStyle(e).animationName),'none');
 if(width===1440||width===390){await page.evaluate(()=>window.scrollTo({top:document.querySelector('.success-slider').getBoundingClientRect().top+scrollY-110,behavior:'instant'}));await page.mouse.move(0,0);await page.screenshot({path:path.join(output,(route.includes('placements')?'placements':route==='/results.html'?'result-categories':'result-posters')+'-slider-'+width+'.png')});}
 }console.log('Opposing slides, loop geometry, controls and responsive layout passed at '+width+'px');}
 await open('/results.html');await page.locator('.success-toggle').click();await page.locator('.success-group:not([data-slider-clone]) > .result-poster-card:not([data-slider-clone]) a[href="/results/ca.html"]').click();await page.waitForURL('**/results/ca.html');await page.locator('.success-slider').waitFor();await page.locator('.success-toggle').click();await page.locator(unique+' button').first().click();await page.locator('.image-lightbox.open').waitFor();await page.keyboard.press('Escape');assert.equal(await page.locator('.image-lightbox.open').count(),0);
 await open('/placements.html');await page.locator(unique+' button').first().focus();assert.equal(await page.locator('.success-track').first().evaluate(e=>getComputedStyle(e).animationName),'none');await page.keyboard.press('Enter');await page.locator('.image-lightbox.open').waitFor();await page.keyboard.press('Escape');
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto(base+'/placements.html');await page.locator('.success-slider').waitFor();assert.equal(await page.locator('.success-track').first().evaluate(e=>getComputedStyle(e).animationName),'none');assert.equal(await page.locator('[data-slider-clone]:visible').count(),0);assert.equal(await page.locator(unique).count(),6);
 await page.emulateMedia({reducedMotion:'no-preference'});const settings=(await api('/api/admin/settings')).settings;await api('/api/admin/settings','PUT',{animations:{...settings.animations,enabled:false}});await page.goto(base+'/results.html');await page.waitForLoadState('networkidle');assert.equal(await page.locator('.success-track').first().evaluate(e=>getComputedStyle(e).animationName),'none');
 await page.context().addCookies([{name:cookie.split('=')[0],value:cookie.slice(cookie.indexOf('=')+1),url:base}]);await page.goto(base+'/results.html?cms_edit=1');assert.equal(await page.locator('.success-slider').count(),0);assert.equal(await page.locator('.result-poster-card').count(),6);
 for(let i=1;i<6;i++)await api('/api/admin/content/placement_posters/slide-'+i,'DELETE');await page.goto(base+'/placements.html');assert.equal(await page.locator('.success-slider.is-single').count(),1);assert.equal(await page.locator('[data-slider-clone]').count(),0);await api('/api/admin/content/placement_posters/slide-0','DELETE');await page.goto(base+'/placements.html');assert.equal(await page.locator('.success-slider').count(),0);
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'sliders.json'),JSON.stringify({passed:true,widths:[1440,768,390,360],routes:['/results.html','/results/ca.html','/placements.html'],checks:['two opposite directions','seamless group geometry','unique records and drafts','pause/play','category link navigation','poster lightbox and keyboard','reduced motion and global animation switch','Page Editor unchanged','one and zero poster states'],errors},null,2));console.log('All slider checks passed.');
 }catch(e){await page.screenshot({path:path.join(output,'slider-error.png')});throw e;}finally{await browser.close();await new Promise(r=>server.close(r));await db.close();fs.rmSync(process.env.DEV_DATABASE_DIR,{recursive:true,force:true});}process.exit(0);
})().catch(e=>{console.error(e);process.exit(1)});
