const express=require('express'),bcrypt=require('bcryptjs'),crypto=require('crypto'),OTP=require('otpauth'),QR=require('qrcode');const {rateLimit}=require('express-rate-limit');
const sha=s=>crypto.createHash('sha256').update(String(s)).digest('hex');
function seal(secret){const key=Buffer.from(process.env.TOTP_ENCRYPTION_KEY||'','hex');if(key.length!==32)throw Error('Set TOTP_ENCRYPTION_KEY to 64 hex characters');const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv);return [iv.toString('hex'),Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]).toString('hex'),cipher.getAuthTag().toString('hex')].join('.');}
function unseal(value){const [iv,body,tag]=value.split('.'),d=crypto.createDecipheriv('aes-256-gcm',Buffer.from(process.env.TOTP_ENCRYPTION_KEY,'hex'),Buffer.from(iv,'hex'));d.setAuthTag(Buffer.from(tag,'hex'));return Buffer.concat([d.update(Buffer.from(body,'hex')),d.final()]).toString('utf8');}
const totp=(secret,user)=>new OTP.TOTP({issuer:'Logic CMS',label:user,algorithm:'SHA1',digits:6,period:30,secret:OTP.Secret.fromBase32(secret)});
const regenerate=req=>new Promise((resolve,reject)=>req.session.regenerate(e=>e?reject(e):resolve()));
function auth(db){const r=express.Router();
 const loginLimit=rateLimit({windowMs:15*60*1000,limit:15,standardHeaders:'draft-7',legacyHeaders:false,message:{ok:false,error:'Too many attempts. Try again in 15 minutes.'}});
 const otpLimit=rateLimit({windowMs:15*60*1000,limit:10,standardHeaders:'draft-7',legacyHeaders:false,message:{ok:false,error:'Too many verification attempts. Try later.'}});
 const user=async name=>(await db.query('SELECT * FROM admin_users WHERE username=$1',[name])).rows[0];
 const requireUser=async(req,res,next)=>{const u=req.session.username&&await user(req.session.username);if(!u||u.session_version!==req.session.version||Date.now()>(req.session.createdAt||0)+12*3600000)return res.status(401).json({ok:false,error:'Sign in required'});req.adminUser=u;next();};
 async function verifyOtp(u,token){if(!u.totp_secret)return true;token=String(token||'').trim();if(/^\d{6}$/.test(token)){const t=totp(unseal(u.totp_secret),u.username),delta=t.validate({token,window:1});if(delta===null)return false;const step=Math.floor(Date.now()/30000)+delta;return (await db.query('UPDATE admin_users SET last_totp_step=$1 WHERE username=$2 AND last_totp_step<$1 RETURNING username',[step,u.username])).rows.length===1;}
 const hash=sha(token.toLowerCase()),codes=u.recovery_codes||[];if(!codes.includes(hash))return false;return (await db.query('UPDATE admin_users SET recovery_codes=recovery_codes-$1 WHERE username=$2 AND recovery_codes ? $1 RETURNING username',[hash,u.username])).rows.length===1;}
 r.get('/session',async(req,res)=>{const u=req.session.username&&await user(req.session.username),valid=!!u&&u.session_version===req.session.version&&Date.now()<(req.session.createdAt||0)+12*3600000;req.session.csrf||=crypto.randomBytes(32).toString('hex');res.json({ok:true,authenticated:valid,user:valid?u.username:null,csrfToken:req.session.csrf});});
 r.post('/login',loginLimit,async(req,res)=>{const u=await user(String(req.body.username||''));const valid=u&&await bcrypt.compare(String(req.body.password||''),u.password_hash);if(!valid||!(await verifyOtp(u,req.body.otp)))return res.status(401).json({ok:false,error:'Invalid login or verification code'});await regenerate(req);req.session.username=u.username;req.session.version=u.session_version;req.session.createdAt=Date.now();req.session.csrf=crypto.randomBytes(32).toString('hex');res.json({ok:true,csrfToken:req.session.csrf});});
 r.post('/logout',(req,res)=>req.session.destroy(()=>res.clearCookie('logic_admin_session',{path:'/'}).json({ok:true})));
 r.post('/change-password',requireUser,otpLimit,async(req,res)=>{if(!await bcrypt.compare(String(req.body.currentPassword||''),req.adminUser.password_hash))return res.status(400).json({ok:false,error:'Current password is incorrect'});const p=String(req.body.newPassword||'');if(p.length<12||Buffer.byteLength(p)>72)return res.status(400).json({ok:false,error:'Password must be 12–72 bytes'});await db.query('UPDATE admin_users SET password_hash=$1,session_version=session_version+1 WHERE username=$2',[await bcrypt.hash(p,12),req.adminUser.username]);req.session.destroy(()=>res.clearCookie('logic_admin_session').json({ok:true,message:'Password changed. Sign in again.'}));});
 r.get('/2fa',requireUser,(req,res)=>res.json({ok:true,enabled:!!req.adminUser.totp_secret,recoveryRemaining:req.adminUser.recovery_codes.length}));
 r.post('/2fa/setup',requireUser,otpLimit,async(req,res)=>{if(req.adminUser.totp_secret)return res.status(409).json({ok:false,error:'2FA is already enabled'});if(!await bcrypt.compare(String(req.body.password||''),req.adminUser.password_hash))return res.status(403).json({ok:false,error:'Password confirmation required'});const secret=new OTP.Secret({size:20}).base32;seal(secret);req.session.pendingTotp={secret,expires:Date.now()+600000};const uri=totp(secret,req.adminUser.username).toString();res.json({ok:true,qr:await QR.toDataURL(uri),secret});});
 r.post('/2fa/enable',requireUser,otpLimit,async(req,res)=>{const p=req.session.pendingTotp;if(!p||p.expires<Date.now()||totp(p.secret,req.adminUser.username).validate({token:String(req.body.otp||''),window:1})===null)return res.status(400).json({ok:false,error:'Invalid or expired setup code'});const codes=Array.from({length:10},()=>crypto.randomBytes(6).toString('hex'));await db.query('UPDATE admin_users SET totp_secret=$1,recovery_codes=$2,last_totp_step=$3,session_version=session_version+1 WHERE username=$4',[seal(p.secret),JSON.stringify(codes.map(sha)),Math.floor(Date.now()/30000),req.adminUser.username]);req.session.version++;delete req.session.pendingTotp;res.json({ok:true,recoveryCodes:codes});});
 r.post('/2fa/disable',requireUser,otpLimit,async(req,res)=>{if(!await bcrypt.compare(String(req.body.password||''),req.adminUser.password_hash)||!await verifyOtp(req.adminUser,req.body.otp))return res.status(403).json({ok:false,error:'Password and current code required'});await db.query('UPDATE admin_users SET totp_secret=NULL,recovery_codes=$1,last_totp_step=-1,session_version=session_version+1 WHERE username=$2',['[]',req.adminUser.username]);req.session.version++;res.json({ok:true});});
 return {router:r,requireUser};}
module.exports={auth,seal,unseal};
