require('dotenv').config({quiet:true});
const express=require('express'),session=require('express-session'),helmet=require('helmet'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {connect,root}=require('./services/db'),{seed}=require('./services/seed'),content=require('./services/content'),render=require('./services/render'),legacy=require('../server');const {auth}=require('./routes/auth');
async function start(){const prod=process.env.NODE_ENV==='production';if(!process.env.SESSION_SECRET||process.env.SESSION_SECRET.length<32)throw Error('SESSION_SECRET must be at least 32 random characters');if(prod&&(!process.env.PUBLIC_ORIGIN||!process.env.PUBLIC_ORIGIN.startsWith('https://')))throw Error('PUBLIC_ORIGIN must be the production HTTPS origin');
 const db=await connect();await db.migrate();await seed(db);db.cache={};const refresh=async()=>{for(const t of ['programs','blog_posts','result_categories','results','branches','placement_posters','banners'])db.cache[t]=await db.list(t);legacy.setSettings(await db.get('global_settings','site'));};await refresh();
 const app=express();app.disable('x-powered-by');if(process.env.TRUST_PROXY)app.set('trust proxy',process.env.TRUST_PROXY==='1'?1:process.env.TRUST_PROXY);
 app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'",'https:'],scriptSrc:["'self'","'unsafe-inline'",'https://www.googletagmanager.com','https://www.google-analytics.com','https://connect.facebook.net','https://static.cloudflareinsights.com'],styleSrc:["'self'","'unsafe-inline'",'https://fonts.googleapis.com'],imgSrc:["'self'",'data:','https:'],fontSrc:["'self'",'https://fonts.gstatic.com','data:'],connectSrc:["'self'",'https:'],frameSrc:["'self'",'https://www.youtube.com','https://www.youtube-nocookie.com','https://www.googletagmanager.com','https://maps.google.com'],objectSrc:["'none'"],baseUri:["'self'"],formAction:["'self'"],upgradeInsecureRequests:prod?[]:null}},strictTransportSecurity:prod?{maxAge:31536000,includeSubDomains:false}:false,crossOriginEmbedderPolicy:false,referrerPolicy:{policy:'strict-origin-when-cross-origin'},frameguard:{action:'sameorigin'}}));
 app.use('/uploads',(req,res,next)=>{res.set('Content-Security-Policy',"default-src 'none'; sandbox");next();});
 const Store=prod||process.env.DATABASE_URL?require('connect-pg-simple')(session):null;
 app.use(session({name:'logic_admin_session',secret:process.env.SESSION_SECRET,resave:false,saveUninitialized:false,store:Store?new Store({pool:db.raw,tableName:'session'}):undefined,cookie:{httpOnly:true,secure:prod,sameSite:'strict',maxAge:12*3600000}}));
 app.use((req,res,next)=>{if(['GET','HEAD','OPTIONS'].includes(req.method))return next();const origin=process.env.PUBLIC_ORIGIN||`${req.protocol}://${req.get('host')}`;if(req.get('origin')&&req.get('origin')!==origin)return res.status(403).json({ok:false,error:'Invalid request origin'});if(req.path.startsWith('/api/admin/')&&req.path!=='/api/admin/login'){const a=Buffer.from(req.get('x-csrf-token')||''),b=Buffer.from(req.session.csrf||'');if(!a.length||a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(403).json({ok:false,error:'Session check failed. Refresh the admin page.'});}next();});
 app.use((req,res,next)=>{const upload=['/api/admin/media/upload','/api/admin/brochure/upload'].includes(req.path);if(upload&&!req.session.username)return res.status(401).json({ok:false,error:'Sign in required'});express.json({limit:upload?'42mb':'2mb'})(req,res,next);});
 const security=auth(db);app.use('/api/admin',security.router);app.use('/api/admin',security.requireUser);
 app.get('/api/health',async(req,res)=>{await db.query('SELECT 1');res.json({ok:true});});
 app.get('/api/public/settings',async(req,res)=>res.json({ok:true,settings:content.publicSettings(await db.get('global_settings','site'))}));
 app.get('/api/public/brochures',(req,res)=>res.json({ok:true,brochures:legacy.publicBrochureView()}));
 app.use('/api',require('./routes/forms')(db,legacy));
 app.get('/api/brochure/download',(req,res)=>legacy.legacyHandler(req,res));
 app.get('/api/admin/settings',async(req,res)=>res.json({ok:true,settings:await db.get('global_settings','site')}));
 app.put('/api/admin/settings',async(req,res)=>{const allowed=['siteName','tagline','logoUrl','faviconUrl','primaryColor','secondaryColor','phone','whatsapp','email','address','facebook','instagram','youtube','linkedin','socialLinks','announcementEnabled','announcementText','announcementLink','customHeadCode','navigation','footerCourses','animations','typography','brochures','tracking','header','footer'];const input=Object.fromEntries(Object.entries(req.body).filter(([k])=>allowed.includes(k)));const settings={...await db.get('global_settings','site'),...content.validateSettings(input)};await db.put('global_settings','site',settings);legacy.setSettings(settings);res.json({ok:true,settings});});
 app.get('/api/admin/layout/:part',async(req,res)=>{const part=req.params.part;if(!['header','footer'].includes(part))return res.sendStatus(404);const settings=await db.get('global_settings','site');res.json({ok:true,settings,layout:require('./services/layout').config(settings)[part]});});
 app.put('/api/admin/layout/:part',async(req,res)=>{const part=req.params.part;if(!['header','footer'].includes(part))return res.sendStatus(404);try{const input=req.body,keys=part==='header'?['siteName','navigation','whatsapp','announcementEnabled','announcementText','announcementLink']:[ 'siteName','tagline','phone','email','whatsapp','address','footerCourses','socialLinks'];const shared=Object.fromEntries(Object.entries(input.settings||{}).filter(([k])=>keys.includes(k)));const current=await db.get('global_settings','site');const settings={...current,...content.validateSettings(shared),[part]:{...current[part],...require('./services/layout').validate(part,input.layout)}};await db.put('global_settings','site',settings);legacy.setSettings(settings);res.json({ok:true});}catch(e){res.status(400).json({ok:false,error:e.message});}});
 const collection=/^(blog_posts|result_categories|results|programs|branches|placement_posters|banners)$/;
 app.get('/api/public/content/:table',async(req,res)=>{if(!collection.test(req.params.table))return res.sendStatus(404);let items=await db.list(req.params.table);if(req.params.table==='blog_posts')items=items.filter(x=>x.status==='published');else if(['results','placement_posters','banners'].includes(req.params.table))items=items.filter(x=>x.status!=='draft');res.json({ok:true,items});});
 app.get('/api/admin/content/:table',async(req,res)=>{if(!collection.test(req.params.table))return res.sendStatus(404);res.json({ok:true,items:await db.list(req.params.table)});});
 app.put('/api/admin/content/:table/:id',async(req,res)=>{const {table,id}=req.params;if(!collection.test(table)||! /^[a-z0-9-]{1,100}$/.test(id))return res.status(400).json({ok:false,error:'Invalid record identifier'});const data=content.validate(table,req.body);if((table==='results'||table==='banners'&&data.categoryId)&&!await db.get('result_categories',data.categoryId))return res.status(400).json({ok:false,error:'Select an existing result category'});const old=await db.get(table,id);if(table==='blog_posts'&&old&&old.slug!==data.slug)return res.status(400).json({ok:false,error:'Existing article slugs are fixed to preserve working URLs'});await db.put(table,id,{...data,id});await refresh();res.json({ok:true});});
 app.delete('/api/admin/content/:table/:id',async(req,res)=>{const {table,id}=req.params;if(!collection.test(table))return res.sendStatus(404);if(table==='result_categories'&&[...db.cache.results,...db.cache.banners].some(x=>x.categoryId===id))return res.status(409).json({ok:false,error:'Move or remove results before deleting this category'});await db.remove(table,id);await refresh();res.json({ok:true});});
 app.use('/api/admin',require('./routes/media')(db));
 app.delete('/api/admin/media',async(req,res)=>{const target=String(req.query.url||'');if(!/^\/(?:uploads|assets\/(?:images|course-icons))\/[a-zA-Z0-9_./%-]+$/.test(target)||target.includes('..')||target.startsWith('/uploads/brochures/'))return res.status(400).json({ok:false,error:'Invalid media path'});const file=path.resolve(root,'.'+decodeURIComponent(target));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile())return res.status(404).json({ok:false,error:'Media not found'});fs.unlinkSync(file);await db.query('DELETE FROM media_files WHERE url=$1',[target]);res.json({ok:true});});

 const leads=async()=>(await db.query('SELECT id,kind,data,received_at,crm_status FROM contact_submissions ORDER BY received_at DESC LIMIT 10000')).rows.map(x=>({...x.data,id:x.id,kind:x.kind,receivedAt:x.received_at,crmStatus:x.crm_status}));
 app.get('/api/admin/leads',async(req,res)=>res.json({ok:true,leads:await leads()}));
 app.get('/api/admin/leads.csv',async(req,res)=>{const rows=await leads(),keys=[...new Set(rows.flatMap(Object.keys))],cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';res.type('csv').attachment('logic-leads.csv').send([keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\n'));});
 app.delete('/api/admin/leads',async(req,res)=>{await db.query('DELETE FROM contact_submissions');res.json({ok:true});});
 app.get('/api/admin/dashboard',async(req,res)=>res.json({ok:true,stats:{pages:fs.readdirSync(root).filter(x=>x.endsWith('.html')).length+fs.readdirSync(path.join(root,'courses')).length,media:(await db.query('SELECT count(*) FROM media_files')).rows[0].count,leads:(await db.query('SELECT count(*) FROM contact_submissions')).rows[0].count,backups:fs.readdirSync(path.join(root,'data/backups')).length},recentLeads:(await leads()).slice(0,5)}));

 app.put('/api/admin/page',async(req,res,next)=>{if(typeof req.body.html==='string'&&req.query.path==='branches.html'){const $=require('cheerio').load(req.body.html);for(const e of $('[data-branch-id]').toArray()){const n=$(e),id=n.attr('data-branch-id'),old=await db.get('branches',id);if(old)await db.put('branches',id,{...old,name:n.find('h3,h2').first().text(),phone:n.find('a[href^="tel:"]').first().text()});}await refresh();}if(typeof req.body.html==='string' && req.query.path==='index.html'){const $=require('cheerio').load(req.body.html);for(const e of $('[data-record-id]').toArray()){const n=$(e),id=n.attr('data-record-id'),old=await db.get('programs',id);if(!old)continue;const data=content.validate('programs',{...old,title:n.find('h3').text(),description:n.find('p').first().text(),category:n.attr('data-category'),categoryLabel:n.find('.course-tag').text(),duration:n.find('.duration').text(),url:n.find('a').attr('href'),image:n.find('.program-icon img').attr('src')});await db.put('programs',id,{...data,id});}await refresh();}next();});
 // Existing visual editor, files, backups, brochures and Odoo tools retain their contracts.
 app.use('/api/admin',(req,res)=>{req.url='/api/admin'+req.url;return legacy.legacyHandler(req,res);});
 app.use('/api',(req,res)=>res.status(404).json({ok:false,error:'API route not found'}));
 app.use((req,res,next)=>'cms_edit' in req.query?security.requireUser(req,res,next):next());
 async function sendHtml(res,html,status=200,preview=false){const settings=await db.get('global_settings','site');let output=await render.page(html,db,settings,res.req.path);if(!preview){if(settings.customHeadCode)output=output.replace('</head>',()=>String(settings.customHeadCode)+'\n</head>');output=legacy.injectTrackingIntoHtml(output);}res.status(status).set('Cache-Control','no-cache').type('html').send(output);}
 app.get(/^\/blog\/([a-z0-9-]+)\.html$/,async(req,res)=>{const slug=req.params[0],p=db.cache.blog_posts.find(x=>x.slug===slug&&x.status==='published');if(!p)return sendHtml(res,fs.readFileSync(path.join(root,'404.html'),'utf8'),404);return sendHtml(res,render.shell(p.title,`<section class="article-hero"><div class="container article-hero-inner"><a href="/blog.html">← Back to Blog</a><span class="eyebrow">${content.esc(p.category)}</span><h1>${content.esc(p.title)}</h1><p>${content.esc(p.author)}${p.publishedDate?' · '+content.esc(p.publishedDate):''}</p></div></section><main class="section"><article class="container article-body">${p.thumbnail?`<img class="article-thumbnail" src="${content.esc(p.thumbnail)}" alt="${content.esc(p.title)}">`:''}${content.clean(p.content)}</article></main>`));});
 app.get(/^\/results\/([a-z0-9-]+)\.html$/,async(req,res)=>{const cat=db.cache.result_categories.find(x=>x.id===req.params[0]);if(!cat)return sendHtml(res,fs.readFileSync(path.join(root,'404.html'),'utf8'),404);const items=db.cache.results.filter(x=>x.categoryId===cat.id&&x.status!=='draft'),groups=[...new Set(items.map(x=>x.level||'Results'))];const body=groups.map(level=>`<section class="section"><div class="container"><h2>${content.esc(level)}</h2><div class="result-poster-grid">${items.filter(x=>(x.level||'Results')===level).map(content.result).join('')}</div></div></section>`).join('')||'<section class="section"><div class="container"><p>Results will be published here when available.</p></div></section>';return sendHtml(res,render.shell(cat.title,`<main><section class="page-hero"><div class="container"><a href="/results.html">← All Results</a><h1>${content.esc(cat.title)}</h1><p>${content.esc(cat.description)}</p></div></section>${body}</main>`));});
 // Strict static allowlist: internals, backups, environment and git history cannot be downloaded.
 app.use(async(req,res)=>{let pathname;try{pathname=decodeURIComponent(req.path);}catch{return res.sendStatus(400)}if(pathname.includes('..')||pathname.includes('\\')||pathname.split('/').some(x=>x.startsWith('.')))return res.sendStatus(403);
 if(pathname.startsWith('/uploads/brochures/'))return res.sendStatus(403);
 if(!/^\/(?:assets\/|uploads\/|admin\/|courses\/|[a-z0-9-]+\.html$|robots\.txt$|sitemap\.xml$|$)/i.test(pathname))return res.sendStatus(404);
 let file=path.join(root,pathname==='/'?'index.html':pathname);if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.existsSync(file))return sendHtml(res,fs.readFileSync(path.join(root,'404.html'),'utf8'),404);
 if(file.endsWith('.html')&&!pathname.startsWith('/admin/'))return sendHtml(res,fs.readFileSync(file,'utf8'),200,!!req.adminUser&&'cms_edit'in req.query);
 if(!/\.(?:html|css|js|png|jpe?g|webp|gif|svg|ico|xml|txt)$/i.test(file))return res.sendStatus(403);res.set('Cache-Control',pathname.startsWith('/admin/')?'no-store':'public, max-age=3600');res.sendFile(file);
 });
 app.use((err,req,res,next)=>{if(res.headersSent)return next(err);const status=err.status===413?413:err.code==='23505'?409:400;console.error('Request failed:',err.code||err.name);res.status(status).json({ok:false,error:status===413?'Upload is too large. Server limit is 20 MB for images.':status===409?'This record already exists.':err.message?.startsWith('Set TOTP')?err.message:'Unable to complete request. Check the fields and try again.'});});
 const server=app.listen(Number(process.env.PORT||8080),process.env.HOST||'127.0.0.1',()=>console.log('Logic CMS ready on port '+(process.env.PORT||8080)));
 await new Promise((resolve,reject)=>{server.once('listening',resolve);server.once('error',reject);});
 return {app,server,db};}
if(require.main===module)start().catch(e=>{console.error(e.message);process.exitCode=1});module.exports={start};
