(()=>{'use strict';const $=s=>document.querySelector(s),T=window.CMSTools,api=T.api;let table='blog_posts',selected=null,categories=[],records=[],dirty=false;
 const fields={blog_posts:[['title','Title'],['slug','URL slug'],['thumbnail','Thumbnail','image'],['excerpt','Short excerpt','textarea'],['content','Full article (formatted HTML)','html'],['author','Author'],['publishedDate','Published date','date'],['category','Category'],['status','Status','status']],programs:[['title','Course title'],['category','Filter category','category'],['categoryLabel','Category label'],['description','Description','textarea'],['duration','Duration'],['url','Course link'],['image','Icon / image','image'],['order','Sort order','number']],result_categories:[['title','Category title'],['thumbnail','Main Results page thumbnail','image'],['description','Course result page introduction','textarea'],['order','Sort order','number']],results:[['categoryId','Course result page','resultCategory'],['level','Level (e.g. CA Foundation)'],['title','Poster title'],['image','Result poster','image'],['examSession','Exam session'],['year','Year','number'],['studentName','Student name'],['rank','Rank'],['status','Visibility','status'],['order','Sort order','number']],placement_posters:[['title','Poster title'],['image','Placement poster','image'],['studentName','Student name'],['course','Course'],['company','Company'],['jobTitle','Job title'],['year','Year','number'],['status','Visibility','status'],['order','Sort order','number']],banners:[['title','Banner name / image description'],['image','Banner image','image'],['page','Show on page','page'],['categoryId','Results destination','optionalCategory'],['caption','Caption (optional)'],['url','Click-through link (optional)'],['status','Visibility','status'],['order','Sort order','number']],branches:[['name','Branch name'],['phone','Branch phone'],['order','Sort order','number']]};
 const titles={blog_posts:'Blog',programs:'Programmes',result_categories:'Result categories',results:'Result posters',placement_posters:'Placement posters',banners:'Banners',branches:'Branches'};
 function status(t,error=false){$('#status').textContent=t;$('#status').style.color=error?'#ae2929':'#166c38';}
 function navigate(next){if(dirty&&!confirm('Discard unsaved changes?'))return;table=next;$('#contentPanel').hidden=false;$('#securityPanel').hidden=true;history.replaceState(null,'','#'+table);load();}
 function list(){const q=$('#recordSearch').value.toLowerCase(),cat=$('#courseFilter').value;$('#records').replaceChildren();for(const x of records.filter(x=>JSON.stringify([x.title,x.name,x.studentName,x.company]).toLowerCase().includes(q)&&(!cat||x.categoryId===cat))){const b=document.createElement('button');b.className='secondary cms-record-button'+(selected?.id===x.id?' active':'');const src=x.thumbnail||x.image;if(src){const img=document.createElement('img');img.src=src;img.alt='';img.className='cms-record-thumb';b.append(img);}const span=document.createElement('span');span.textContent=(x.title||x.name||x.studentName||x.id)+(x.status==='draft'?' · Draft':'');b.append(span);b.onclick=()=>{if(dirty&&!confirm('Discard unsaved changes?'))return;edit(x);list();};$('#records').append(b);}if(!$('#records').children.length){const p=document.createElement('p');p.textContent='No matching items. Add your first one using the button above.';$('#records').append(p);}}
 async function load(id){try{categories=(await api('/api/admin/content/result_categories')).items;records=(await api('/api/admin/content/'+table)).items;$('#contentTitle').textContent=titles[table];$('#newRecord').textContent='+ Add '+({results:'result poster',placement_posters:'placement poster',banners:'banner',result_categories:'result category',programs:'programme',blog_posts:'article',branches:'branch'}[table]);document.querySelectorAll('[data-table]').forEach(b=>b.classList.toggle('active',b.dataset.table===table));$('#courseFilter').replaceChildren(new Option('All courses',''),...categories.map(x=>new Option(x.title,x.id)));$('#courseFilter').hidden=!['results','banners'].includes(table);$('#recordSearch').value='';edit(records.find(x=>x.id===id)||null);list();}catch(e){status(e.message,true)}}
 function edit(record){selected=record;dirty=false;const container=$('#fields');container.replaceChildren();if(!record&&table==='result_categories'){const l=document.createElement('label');l.textContent='Page address (e.g. ca or cma-usa)';const i=document.createElement('input');i.name='id';i.required=true;i.pattern='[a-z0-9]+(-[a-z0-9]+)*';l.append(i);container.append(l);}
 for(const [key,title,type]of fields[table]){const label=document.createElement('label');label.textContent=title;let input;if(['status','category','resultCategory','optionalCategory','page'].includes(type)){input=document.createElement('select');let opts=type==='status'?[['published','Published'],['draft','Draft / hidden']]:type==='category'?[['indian','Indian'],['international','International'],['integrated','Integrated'],['skill / international','Skill / International']]:type==='page'?[['results','Results'],['placements','Placements']]:categories.map(c=>[c.id,c.title]);if(type==='optionalCategory')opts.unshift(['','Main Results page']);for(const [v,t]of opts)input.add(new Option(t,v));}else if(type==='textarea'||type==='html'){input=document.createElement('textarea');label.className='wide';if(type==='html')input.rows=15;}else{input=document.createElement('input');input.type=type==='date'?'date':type==='number'?'number':'text';}input.name=key;const fallback=key==='status'?(table==='blog_posts'?'draft':'published'):key==='order'?0:key==='page'?'results':type==='category'?'indian':type==='resultCategory'?($('#courseFilter').value||categories[0]?.id||''):'';input.value=record?.[key]??fallback;if(['title','slug','name','image'].includes(key)||type==='resultCategory')input.required=true;if(key==='slug'&&record)input.readOnly=true;label.append(input);if(type==='image'){label.className='wide';label.append(T.imageControl(input,e=>status(e,true)));}container.append(label);}
 if(table==='banners'){const page=container.querySelector('[name=page]'),category=container.querySelector('[name=categoryId]');const toggle=()=>{category.closest('label').hidden=page.value!=='results';if(page.value!=='results')category.value='';};page.addEventListener('change',toggle);toggle();}
 $('#deleteRecord').hidden=!record;const link=$('#viewRecord');const route=record?(table==='result_categories'?'/results/'+record.id+'.html':table==='results'?'/results/'+record.categoryId+'.html':table==='placement_posters'?'/placements.html':table==='banners'?record.page==='placements'?'/placements.html':record.categoryId?'/results/'+record.categoryId+'.html':'/results.html':table==='blog_posts'?'/blog/'+record.slug+'.html':table==='programs'?record.url:''):'';link.hidden=!route;if(route)link.href=route;
 }
 $('#recordForm').addEventListener('input',()=>dirty=true);$('#recordForm').addEventListener('change',()=>dirty=true);
 $('#recordForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));let id=selected?.id||data.id||(table==='blog_posts'?data.slug:table.replaceAll('_','-')+'-'+crypto.randomUUID());delete data.id;const b=e.submitter;b.disabled=true;try{await api('/api/admin/content/'+table+'/'+encodeURIComponent(id),{method:'PUT',body:{...selected,...data}});dirty=false;await load(id);status(data.status==='draft'?'Saved as draft. Hidden from the public website.':'Saved. The website is updated.');}catch(e){status(e.message,true)}finally{b.disabled=false}};
 $('#deleteRecord').onclick=async()=>{if(!selected||!confirm('Delete this item from the website? Its image will stay in Media Library.'))return;try{await api('/api/admin/content/'+table+'/'+selected.id,{method:'DELETE'});dirty=false;await load();status('Item deleted.');}catch(e){status(e.message,true)}};
 document.querySelectorAll('[data-table]').forEach(b=>b.onclick=()=>navigate(b.dataset.table));$('#newRecord').onclick=()=>{if(dirty&&!confirm('Discard unsaved changes?'))return;edit(null);list();};$('#recordSearch').oninput=list;$('#courseFilter').onchange=list;
 async function refreshMedia(){const media=await T.reloadMedia();$('#mediaPicker').replaceChildren(...media.map(m=>new Option(m.name,m.url)));}
 $('#upload').onchange=async e=>{try{const url=await T.upload(e.target.files[0]);await refreshMedia();$('#mediaPicker').value=url;status('Uploaded. Copy the URL or choose this image in a record.');}catch(e){status(e.message,true)}};
 $('#copyMedia').onclick=()=>navigator.clipboard.writeText($('#mediaPicker').value).then(()=>status('Image URL copied')).catch(()=>status($('#mediaPicker').value));
 window.addEventListener('hashchange',()=>{const [next,id]=location.hash.slice(1).split('/');if(!fields[next])return;if(dirty&&!confirm('Discard unsaved changes?')){history.replaceState(null,'','#'+table);return;}table=next;$('#contentPanel').hidden=false;$('#securityPanel').hidden=true;load(id);});
 window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
 async function twoStatus(){const d=await api('/api/admin/2fa');$('#twoStatus').textContent=d.enabled?`Enabled · ${d.recoveryRemaining} recovery codes remaining`:'Not enabled';$('#setup2fa').hidden=d.enabled;$('#disable2fa').hidden=!d.enabled;}
 $('#securityTab').onclick=async()=>{$('#contentPanel').hidden=true;$('#securityPanel').hidden=false;try{await twoStatus()}catch(e){status(e.message,true)}};
 $('#setup2fa').onclick=async()=>{try{const d=await api('/api/admin/2fa/setup',{method:'POST',body:{password:$('#confirmPassword').value}});$('#qr').src=d.qr;$('#secret').textContent=d.secret;$('#setupDetails').hidden=false;$('#enable2fa').hidden=false;status('Scan the QR code, then enter the six-digit code.');}catch(e){status(e.message,true)}};
 $('#enable2fa').onclick=async()=>{try{const d=await api('/api/admin/2fa/enable',{method:'POST',body:{otp:$('#otp').value}});$('#recovery').hidden=false;$('#recovery').textContent='Save these recovery codes in a safe place. Each works once.\n\n'+d.recoveryCodes.join('\n');$('#setupDetails').hidden=true;$('#secret').textContent='';$('#qr').removeAttribute('src');$('#enable2fa').hidden=true;$('#otp').value='';$('#confirmPassword').value='';await twoStatus();status('Two-step verification enabled');}catch(e){status(e.message,true)}};
 $('#disable2fa').onclick=async()=>{try{await api('/api/admin/2fa/disable',{method:'POST',body:{password:$('#confirmPassword').value,otp:$('#otp').value}});$('#recovery').hidden=true;$('#otp').value='';$('#confirmPassword').value='';await twoStatus();status('Two-step verification disabled');}catch(e){status(e.message,true)}};
 (async()=>{try{if(!await T.start())return;await refreshMedia();const [tab,id]=location.hash.slice(1).split('/');if(fields[tab])table=tab;await load(id);if(location.hash==='#security')$('#securityTab').click();}catch(e){status(e.message,true)}})();})();