const sanitize=require('sanitize-html'),cheerio=require('cheerio');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeUrl(s){s=String(s||'').trim();if(!s)return '';if(/^(https?:\/\/|mailto:|tel:|\/[^/]|#)/i.test(s))return s;if(/^[\w.-]+(?:\/|\.html)/.test(s)&&!s.includes('..'))return '/'+s;throw Error('Use a relative site URL or an https:// URL');}
function clean(html){return sanitize(String(html||''),{allowedTags:sanitize.defaults.allowedTags.concat(['img','section','article','span']),allowedAttributes:{...sanitize.defaults.allowedAttributes,'*':['class'],img:['src','alt','width','height','loading'],a:['href','target','rel']},allowedSchemes:['https','http','mailto','tel'],allowProtocolRelative:false});}
function validate(table,input){const d={...input};delete d.id;
 for(const [k,v] of Object.entries(d)){if(typeof v==='string'&&v.length>200000)throw Error('Field too long');if(['image','thumbnail','url'].includes(k))d[k]=safeUrl(v);}
 if('order' in d&&(!Number.isFinite(Number(d.order))||Math.abs(Number(d.order))>100000))throw Error('Invalid sort order');if('order' in d)d.order=Number(d.order);
 if(table==='blog_posts'){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(d.slug||''))throw Error('Slug must use lowercase letters, numbers and hyphens');if(!['draft','published'].includes(d.status))throw Error('Choose draft or published');if(d.publishedDate&&!/^\d{4}-\d{2}-\d{2}$/.test(d.publishedDate))throw Error('Use YYYY-MM-DD for the date');d.content=clean(d.content);}
 if(['blog_posts','programs','result_categories'].includes(table)&&!String(d.title||'').trim())throw Error('Title required');
 if(['results','placement_posters','banners'].includes(table)){if(!d.image)throw Error('Choose or upload an image');if(d.status&&!['draft','published'].includes(d.status))throw Error('Choose Draft or Published');}
 if(table==='banners'&&!['results','placements'].includes(d.page))throw Error('Choose the banner page');
 if(table==='results'&&(!d.categoryId||!d.image))throw Error('Result category and poster required');
 if(table==='banners'&&d.page==='placements')d.categoryId='';
 if(table==='branches'&&(!d.name||!d.phone))throw Error('Branch name and phone required');
 return d;
}
function program(p){return `<article class="program-card" data-category="${esc(p.category)}" data-record-id="${esc(p.id)}" data-cms-key="program-${esc(p.id)}"><div class="program-icon"><img src="${esc(p.image)}" alt="" width="40" height="40" loading="lazy"></div><span class="course-tag">${esc(p.categoryLabel||p.category)}</span><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><div class="duration">${esc(p.duration)}</div><a href="${esc(p.url)}" aria-label="View ${esc(p.title)}"></a></article>`;}
function blogCard(p){return `<article class="blog-card" data-category="${esc(p.category)}"><a class="blog-card-link" href="/blog/${esc(p.slug)}.html"><div class="blog-card-visual visual-${esc(p.category)}">${p.thumbnail?`<img src="${esc(p.thumbnail)}" alt="${esc(p.title)}" loading="lazy">`:`<span class="blog-visual-kicker">${esc(p.categoryLabel||p.category)}</span><strong>${esc(p.title)}</strong>`}</div><div class="blog-card-copy"><span class="course-tag">${esc(p.category)}</span><h3>${esc(p.title)}</h3><p>${esc(p.excerpt)}</p><span>Read guide →</span></div></a></article>`;}
function category(c){return `<article class="result-poster-card"><a class="result-category-link" href="/results/${esc(c.id)}.html"><div class="result-poster-media"><img src="${esc(c.thumbnail)}" alt="${esc(c.title)}" loading="lazy"></div><div class="result-poster-copy"><h3>${esc(c.title)}</h3><span>View results →</span></div></a></article>`;}
function result(r){return `<article class="result-poster-card"><button type="button" class="result-poster-media" data-image-lightbox="${esc(r.image)}" aria-label="Enlarge ${esc(r.studentName||r.title||'result')}"><img src="${esc(r.image)}" alt="${esc(r.title||r.studentName||'Result poster')}" loading="lazy"></button><div class="result-poster-copy"><div><span>${esc([r.examSession,r.year].filter(Boolean).join(' · '))}</span><h3>${esc(r.studentName||r.title||r.level)}</h3><p>${esc(r.rank?'Rank '+r.rank:'')}</p></div></div></article>`;}
const publicSettings=s=>{const o={...s};delete o.brochures;delete o.customHeadCode;return o;};
function validateSettings(input){const d={...input};for(const part of ['header','footer'])if(part in d)d[part]=require('./layout').validate(part,d[part]);for(const k of ['logoUrl','faviconUrl','announcementLink','facebook','instagram','youtube','linkedin'])if(k in d)d[k]=safeUrl(d[k]);for(const k of ['primaryColor','secondaryColor'])if(k in d&&!/^#[a-f\d]{6}$/i.test(d[k]))throw Error('Invalid brand colour');for(const k of ['navigation','footerCourses','socialLinks'])if(k in d){if(!Array.isArray(d[k]))throw Error('Invalid links');d[k]=d[k].map(x=>({...x,url:safeUrl(x.url),...(x.iconUrl?{iconUrl:safeUrl(x.iconUrl)}:{})}));}return d;}
module.exports={esc,safeUrl,clean,validate,program,blogCard,category,result,publicSettings,validateSettings};
